version: '3.9'
services:
  app:
    build: .
    container_name: cdelu-app
    ports:
      - "3001:3001"
    env_file:
      - ./env.local
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && node src/index.js"
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: cdelu-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trigamer_diario
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:


